export const URL = "https://swapi.dev/api/"
export const filmsURL = "films/?format=json"
export const charactersURL = "people/?format=json"
export const planetsURL = "planets/?format=json"
export const speciesURL = "species/?format=json"
export const starshipsURL = "starships/?format=json"
export const vehiclesURL = "vehicles/?format=json"